kind: Secret
apiVersion: v1
metadata:
  name: app-crds
  annotations:
    avp.kubernetes.io/path: "credentials/data/solar-system-app"
type: Opaque
stringData:
  password: <password>
  username: <username>
